version: "3.8"
services:
  postgres:
    image: postgres:16.0
    container_name: audio_service_container
    environment:
      POSTGRES_DB: "music_lover"
      POSTGRES_USER: "roman"
      POSTGRES_PASSWORD: "6666"
    volumes:
      - ./db-postgres/postgres-data:/var/lib/postgresql/data
    ports:
      - "3030:5432"