spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: audio-service
          uri: lb://AUDIO-SERVICE
          predicates: Path=/catalog/songs/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/musichub

server:
  port: 8088
