spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: audio-service
          uri: lb://AUDIO-SERVICE
          predicates: Path=/catalog/**
        - id: search-audio-service
          uri: lb://SEARCH-AUDIO-SERVICE
          predicates: Path=/search/**
#        - id: notification-service
#          uri: lb://NOTIFACTION-SERVICE
#          predicates: Path/subscription/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/musichub

server:
  port: 8088
