spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: audio-service
          uri: lb://AUDIO-SERVICE
          predicates: Path=/catalog/songs/**

server:
  port: 8088
