spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: audio-service
          uri: lb://AUDIO-SERVICE
          predicates:
          - Path=/songs/**, /authors/**
        - id: search-audio-service
          uri: lb://SEARCH-AUDIO-SERVICE
          predicates: Path=/search/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri:

server:
  port: 8088
