spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: audio-service
          uri: lb://AUDIO-SERVICE
          predicates: Path=/catalog/**
        - id: search-audio-service
          uri: lb://SEARCH-AUDIO-SERVICE
          predicates: Path=/search/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:

server:
  port: 8088
