spring:
  application:
    name: audio-service
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false

server:
  port: 8083
