spring:
  application:
    name: audio-service
  datasource:
    url: jdbc:postgresql://localhost:3030/music_hub
    username: roman
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false

  liquibase:
    change-log: db/changelog/changelog-master.xml

server:
  port: 8083
