spring:
  application:
    name: search-audio-service
  datasource:
    url: jdbc:postgresql://localhost:3030/music_lover
    username: roman
    password: 6666
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false

server:
  port: 8082
